dataset:
  speech_metadata_path: "VoxCeleb2.csv"
  size:
    train: 16384
    valid: 1024
  wave_length: 64000
  sample_rate: 16000
  fps: 16
  n_spks_probs: [0.0, 0.1, 0.8, 0.1]
  augmentation:
    probability: 0.0
    volume:
      lowest: 0.75
      highest: 1.25


dataloader:  
  n_workers: 2
  batch_size_per: 1
  

optimizer:
  name: torch.optim.Adam
  args:
    lr: 0.001
    weight_decay: 0.01
    betas: [0.9, 0.999]
  

scheduler:
    name: torch.optim.lr_scheduler.ReduceLROnPlateau
    args:
        mode: "min"
        factor: 0.5
        patience: 8
        cooldown: 0
        min_lr: 1.0e-6


trainer:
  # gpus: 1
  n_epochs: 200
  save_frequency: 4